### PR TITLE
[dashing backport] MAX_STRING_SIZE increase

### PR DESCRIPTION
**Pull request by zmichaels11**
Dashing backport of #487

### CODE REVIEW

**Comment by zmichaels11** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8166/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4148/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6651/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8046/)

**Comment by dirk-thomas** [comment]
The patch looks fine to me but the CI builds seem to test master not dashing?

**Comment by tfoote** [comment]
@zmichaels11 please relaunch CI using a repos file that's branched from the dashing branch. https://github.com/ros2/ros2/blob/dashing/ros2.repos

**Comment by zmichaels11** [comment]
Trying again, but with dashing
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8178/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4157/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6660/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8055/)

**Comment by zmichaels11** [comment]
@dirk-thomas its passing now

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks for making the backport.

**Pull request merged**
