### PR TITLE
Generate version header using `ament_generate_version_header(..)`

### LINKED ISSUE #1139: Adding `ament_generate_version_header(..)` to these packages?
#### Feature description
Would it be OK to add a call to `ament_generate_version_header(..)` to the `CMakeLists.txt` of the packages in this repository to allow dependent packages to check for specific (minimum) versions?

According to [the Changelog](https://docs.ros.org/en/humble/Releases/Release-Humble-Hawksbill.html#ament-cmake-gen-version-h) this is supported since Humble, and would be of great use to packages which desire to conditionally compile specific code paths (avoid branching, etc).

AFAICT, only `rclcpp` currently exports that header (ros2/rclcpp#1886), so the suggestion is to add it to `rcl` (and a bunch of other *core packages* as well).

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Would fix #1139.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I'm pretty sure the test failures are unrelated to the changes in this PR.

**Comment by gavanderhoorn** [comment]
A similar PR on `rcpputils`: ros2/rcpputils#190.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by gavanderhoorn** [comment]
I noticed ros2/rcpputils#190 adds a `buildtool_depend` on `ament_cmake_gen_version_h`.

Is that necessary? Or does the already present `ament_cmake` take care of that?

**Comment by clalancette** [comment]
> Is that necessary? Or does the already present `ament_cmake` take care of that?

It's necessary; it is a separate package.

**Comment by gavanderhoorn** [comment]
Fixed.

**Review by mjcarroll — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Friendly ping.

**Comment by gavanderhoorn** [comment]
Realised I forgot to `find_package(ament_cmake_gen_version_h)`.

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20652/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14981/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21354/)

**Comment by gavanderhoorn** [comment]
Thanks for the review(s) and merging this @fujitatomoya.

Would there be any way this could be backported to Humble and Iron?

IIUC, `ament_cmake_gen_version_h` is available there as well.

**Comment by fujitatomoya** [comment]
@Mergifyio barkport iron humble

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron humble

**Pull request merged**
