### PR TITLE
[Foxy backport] Improve error message for malformed YAML files

### PR DESCRIPTION
**Pull request by simutisernestas**
Backport #556 to Foxy as mentioned in #815.

### CODE REVIEW

**Comment by simutisernestas** [comment]
i've missed test failing somehow, i'll update it later

**Comment by simutisernestas** [comment]
@jacobperron could you please review the PR?

**Comment by jacobperron** [comment]
@simutisernestas The `__params:=` syntax is invalid in Foxy (it was deprecated in Eloquent and subsequently removed in Foxy). Also, with the latest version of `rcl` in Foxy, we see a reasonable error message (as I commented in https://github.com/ros2/rcl/issues/815#issuecomment-706415060). I don't think this backport is necessary anymore. Can you confirm if this is still an issue in Foxy?

**Comment by simutisernestas** [comment]
Yes, you are right. I get a proper error message now in Foxy.

**Pull request closed without merging**
