### PR TITLE
tests generated for each RMW impl must have unique names to be distinguishable

### PR DESCRIPTION
**Pull request by dirk-thomas**
Otherwise test results in Jenkins are not really tell which version of the test fails: http://ci.ros2.org/job/ci_windows/1114/testReport/(root)/TestSubscriptionFixture/

http://ci.ros2.org/job/ci_windows/1122/testReport/(root)/TestSubscriptionFixture__rmw_connext_dynamic_cpp/

### CODE REVIEW

**Comment by jacquelinekay** [comment]
that's weird. I distinctly remember doing this a while ago, for #21. Maybe my commit got reverted by @wjwwood at some point.

https://github.com/ros2/rcl/pull/21#issuecomment-183125116

**Comment by wjwwood** [comment]
Sorry that was unintentional if I did.

**Comment by jacquelinekay** [comment]
Uncrustify errors due to this PR:

http://ci.ros2.org/view/nightly/job/nightly_osx/235/testReport/junit/projectroot.Users.osrf.jenkins.workspace.nightly_osx.ws.src.ros2.rcl/rcl/uncrustify/

**Comment by dirk-thomas** [comment]
Already fixed in fcee889f553faa37b460e314635273b8ab958a9e

**Comment by jacquelinekay** [comment]
I see, sorry for the noise

**Pull request merged**
