### PR TITLE
Use APPEND_LIBRARY_DIRS option to ament_add_gtest to fix tests on Windows

### PR DESCRIPTION
**Pull request by wjwwood**
This is part of a partial solution to https://github.com/ros2/rcl/issues/8 and an alternative to https://github.com/ros2/rcl/pull/9.

It requires https://github.com/ament/ament_cmake/pull/52.

Connects to ros2/rcl#8

### CODE REVIEW

**Comment by wjwwood** [comment]
Here is a Windows CI job to show it fixes 6 of the failing tests (and one more which fails later in a different way).

I think this should be reviewed and merged and I can fix the other failing tests on Windows afterwards.

**Comment by esteve** [comment]
@wjwwood where's the CI job? The changes look good a priori to me.

**Comment by wjwwood** [comment]
Sorry, here it is: http://ci.ros2.org/job/ci_windows/883/

**Comment by esteve** [comment]
@wjwwood no problem :-) +1

**Pull request merged**
