### PR TITLE
Properly initialize the char array used in type hash calculations.

### PR DESCRIPTION
**Pull request by clalancette**
Previously, we were zero initializing it and only setting up one of its fields.  But that doesn't totally properly initialize it; we really should call rcutils_char_array_init to make sure everything is initialized.  Do that in the live source, as well as in the test for it.

This bug was exposed by https://github.com/ros2/rcutils/pull/478 .  @fujitatomoya @emersonknapp FYI

### CODE REVIEW

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcl/pull/1182
Gist: https://gist.githubusercontent.com/clalancette/60bd5624de4345702c1b549b82cd55a2/raw/0a152da4edb66f4ffc7c43379edeb83bf6e6bb5b/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl
TEST args:  --packages-above rcl
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14568
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21845/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16115/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1349/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22555/)

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Comment by ahcorde** [comment]
should we backport this to `humble` or `iron` ?

**Comment by clalancette** [comment]
> should we backport this to `humble` or `iron` ?

Iron, yes.  This code didn't exist in humble, so not needed there.

**Comment by clalancette** [comment]
@mergifyio backport iron

**Pull request merged**
