### PR TITLE
pass qos to rmw create pub/sub

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros2/ros2/issues/233#issuecomment-227359713

### CODE REVIEW

**Comment by jacquelinekay** [comment]
+1

**Comment by wjwwood** [comment]
I checked all the other rmw functions that take qos and they do it correctly, e.g. clients and services.

**Comment by dirk-thomas** [comment]
+1

**Comment by wjwwood** [comment]
CI:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1482/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1153/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/1496/)

**Comment by wjwwood** [comment]
CI lgtm

**Pull request merged**
