### PR TITLE
validation result should be used to print the error message.

### PR DESCRIPTION
**Pull request by fujitatomoya**
a couple of follow-ups for https://github.com/ros2/rcl/pull/1076

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
I checked entire ROS 2 repo, so far only those 2 places do not use `validation_result` to print the error message.

**Comment by fujitatomoya** [comment]
@mjcarroll can you take a look?

**Review by audrow — APPROVED** [review]
Looks good to me with green CI!

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18925/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13455/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19678/)

**Comment by fujitatomoya** [comment]
CI:
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13473/)

**Pull request merged**
