### PR TITLE
Fix up documentation build for rcl_action when using rosdoc2

### PR DESCRIPTION
**Pull request by hidmic**
Similar to #932. 

CI above `rcl_action`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15255/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9974/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12939/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/15508/)

### CODE REVIEW

**Comment by hidmic** [comment]
In retrospect, it was stupid to major bump before checking whether `rcl_action`, `rcl_lifecyle`, and `rcl_yaml_param_parser` needed API changes as well :facepalm:

**Comment by clalancette** [comment]
> In retrospect, it was stupid to major bump before checking whether `rcl_action`, `rcl_lifecyle`, and `rcl_yaml_param_parser` needed API changes as well facepalm

That's fine, major numbers are cheap :).

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by hidmic** [comment]
Test failures are unrelated. Moving forward.

**Pull request merged**
