### PR TITLE
use rcl_allocator for rcl_lifecycle & namespaced topics

### PR DESCRIPTION
**Pull request by Karsten1987**
connects to ros2/rcl#127

### CODE REVIEW

**Comment by Karsten1987** [comment]
up for review.

**Comment by Karsten1987** [comment]
forgot to link CI:

linux: [Build Status](http://ci.ros2.org/job/ci_linux/2688/)
osx: [Build Status](http://ci.ros2.org/job/ci_osx/2147/)
windows: [Build Status](http://ci.ros2.org/job/ci_windows/2812/)

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2733/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/269/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2198/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/2863/)

**Comment by Karsten1987** [comment]
windows [Build Status](http://ci.ros2.org/job/ci_windows/2869/)

test failures are non-related.

**Pull request merged**
