### PR TITLE
remove debugging statements.

### PR DESCRIPTION
**Pull request by fujitatomoya**
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@clalancette 
CC: @ivanpauno 

minor fix to remove debugging statements, could you take a look?

**Comment by fujitatomoya** [comment]
I do not think that it is related to this PR.

- http://build.ros2.org/job/Rpr__rcl__ubuntu_focal_amd64/220/testReport/projectroot/test/test_subscription__rmw_fastrtps_cpp/

take sequence test, expected 3 messages but failed with only 1 message is taken.

**Comment by clalancette** [comment]
> I do not think that it is related to this PR.

Yeah, agreed, that looks flaky.  Let me kick it again and see if it passes.

@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12007/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7034/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9785/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11943/)

**Comment by clalancette** [comment]
Thanks for the contribution, merging.

**Pull request merged**
