### PR TITLE
Removed deprecated rcl_init_timer()

### PR DESCRIPTION
**Pull request by ahcorde**
Removed deprecated rcl_init_timer() deprecated since `jazzy`

### CODE REVIEW

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21386/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15692/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/895/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22122/)

**Review by clalancette — CHANGES_REQUESTED** [review]
I'm OK with removing this one, but I think we also need to update https://github.com/ros2/ros2_tracing/blob/74ff10b30809907b3799b85d6a0414c21198ab3c/tracetools_trace/tracetools_trace/tools/tracepoints.py#L35 .  FYI @christophebedard

**Comment by christophebedard** [comment]
What needs to be updated? The `ros2:rcl_timer_init` tracepoint is already in the new `rcl_timer_init2()` function.

**Comment by clalancette** [comment]
> What needs to be updated? The `ros2:rcl_timer_init` tracepoint is already in the new `rcl_timer_init2()` function.

Oh, I may have misinterpreted.  I thought maybe https://github.com/ros2/ros2_tracing/blob/74ff10b30809907b3799b85d6a0414c21198ab3c/tracetools_trace/tracetools_trace/tools/tracepoints.py#L35 needed to be updated to `ros2:rcl_timer_init2`?  But I definitely might be wrong about that.

**Comment by christophebedard** [comment]
Yeah, that's a fair assumption. The tracepoint event name is usually very similar to the corresponding function name (because the function name itself is nicely descriptive), but it really doesn't have to.

In this case, the `rcl` function name changed because we added a new argument. I suppose we could record the `bool autostart` value, but I don't see a real need for it, unless someone wants that information.

**Comment by clalancette** [comment]
> Yeah, that's a fair assumption. The tracepoint event name is usually very similar to the corresponding function name (because the function name itself is nicely descriptive), but it really doesn't have to.

Oh, I see.  I thought that the tracetools name needed to match the function name, but now I understand that it just needs to match the tracepoint name (which as you say, is similar to but not exactly the same in this case).

OK, in that case I'm fine with this removal.  Thanks for the info @christophebedard

**Review by clalancette — APPROVED** [review]
This looks good to me with green CI (it looks like Linux may have to be re-run).

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21422/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15707/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/922/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22138/)

**Pull request merged**
