### PR TITLE
Add NULL check in remap.c

### PR DESCRIPTION
**Pull request by nnmm**
Followup to https://github.com/ros2/rcl/issues/878

### CODE REVIEW

**Comment by nnmm** [comment]
I took a second look – calling `rcl_remap_name` with a nullptr in `name` and the `type_bitmask` equal to either `RCL_TOPIC_REMAP` or `RCL_SERVICE_REMAP` is incorrect, right? So that function should return an error instead when it is called like that, which would hopefully also satisfy clang-tidy.

**Review by clalancette — CHANGES_REQUESTED** [review]
Ah, this is a much better fix.  You are right, this is a precondition that should hold, so I like this better.

Could you also add a test that violates this precondition?  Thanks.

**Comment by nnmm** [comment]
Sorry, unfortunately clang-tidy doesn't get it when I add the check to `rcl_remap_name`. But that function is private, so you were right – it can never be called with the invalid combination. I'll do what you initially suggested and also add an explanatory comment. And a test.

Should I add a test that   EXPECT_EQ(RCL_RET_INVALID_ARGUMENT, rcl_remap_copy(&remap_empty, &remap_dst));

**Review by clalancette — APPROVED** [review]
Looks good to me, so I'll approve and run CI.  @ros2/team I'd appreciate another review, since I essentially suggested the code here.

**Comment by clalancette** [comment]
CI (build: `--packages-up-to rcl`, test: `--packages-select rcl`; this seems safe since we are adding a check that shouldn't trigger):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13295/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8228/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11028/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13336/)

**Review by sloretz — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks for the additional approval!  Merging.

**Pull request merged**
