### PR TITLE
chore: Minor style improvements

### PR DESCRIPTION
**Pull request by jmachowinski**
followup to https://github.com/ros2/rcl/pull/1146

These are just style changes suggested by @alsora that I pushed on the wrong branch, and thus did not end up in the PR.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
LGTM, do you mind to sign the commit ?

**Comment by jmachowinski** [comment]
> LGTM, do you mind to sign the commit ?

fixed

**Review by alsora — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20789/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15089/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21472/)

**Comment by jmachowinski** [comment]
Can we merge this ?

**Pull request merged**
