### PR TITLE
call to rmw_init, despite the lack of rmw_shutdown

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros2/rclcpp/pull/207/files#r73983227

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by wjwwood** [comment]
CI:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1693/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1255/)

**Comment by wjwwood** [comment]
Redoing CI now that FastRTPS builds again:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1708/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1270/)

**Comment by wjwwood** [comment]
Only OS X failure is the UDPv6 test, which isn't new.

**Pull request merged**
