### PR TITLE
[foxy backport] Refactor parser.c for better testability (#754)

### PR DESCRIPTION
**Pull request by brawner**
Backports #754 

This one needs to be ABI checked
Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12194/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7178/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9921/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12077/)

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12593/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7559/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10304/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12517/)

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
@brawner I'm not sure why the Fpr job is failing but manually triggered CI looks okay.

**Comment by brawner** [comment]
It might be a missing include that get's picked up in the CI job? I'll try digging into this

**Comment by brawner** [comment]
Added the missing includes to get the Fpr job to pass.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12621/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7584/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10328/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12551/)

**Pull request merged**
