### PR TITLE
[Foxy backport] Use valid clock in case of issue in rcl_timer_init (#795) Store reference to rcl_clock_t instead of copy (#797)

### PR DESCRIPTION
**Pull request by sloretz**
Backport #795 and #797 to Foxy

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM.

It'd be nice to get the CI job to turn green before merging. Looks like an infrastructure issue?

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
Looks like PR job is happy and PR is approved. I'll merge with just the PR job since it's a cherry-pick backport.

**Pull request merged**
