### PR TITLE
Yaml param parser shane review 2

### PR DESCRIPTION
**Pull request by sloretz**
A couple changes for windows:

1: Remove include `uinistd.h`
2: Use size_t for array indexes to eliminate warnings about possible loss of data

### CODE REVIEW

**Comment by sloretz** [comment]
@mikaelarguedas I have not. I know it at least works in my xenial docker container locally, but have not tested OSX or the arm job.

**Comment by mikaelarguedas** [comment]
Can you please run a MacOS job? (linux is not necessary if it works on your machine)

**Comment by sloretz** [comment]
@mikaelarguedas OSX with this branch and `libyaml_vendor` [Build Status](https://ci.ros2.org/job/ci_osx/3660/)

**Comment by mikaelarguedas** [comment]
Thanks :+1:

**Comment by anup-pem** [comment]
Looks good. Will go ahead and merge it.

**Pull request merged**
