### PR TITLE
increase result_timeout to 1 mins from 10 secs.

### PR DESCRIPTION
**Pull request by fujitatomoya**
part of https://github.com/ros2/rcl/issues/1103

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19554/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14067/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20272/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-09-21/33733/2

**Comment by clalancette** [comment]
@sloretz is going to review this one.

**Comment by fujitatomoya** [comment]
I will go ahead to close this one since this is work-around but solution, we are working on the solution. see https://github.com/ros2/rcl/issues/1103#issuecomment-1747875250

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-10-12/34178/1

**Pull request closed without merging**
