### PR TITLE
Fix action tests failing in CI 

### PR DESCRIPTION
**Pull request by apojomovsky**
This PR complements #331 
- Relaxes a bit the timeouts set for the rcl_wait function calls.
- Minor fix in `test_msgs__action__Fibonacci_Goal_Request__fini` function call

### CODE REVIEW

**Comment by apojomovsky** [comment]
CI:
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/5709/)
Linux aarch64: [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/2308/)
Windows: [Build Status](https://ci.ros2.org/job/ci_windows/5622/)
MacOS: [Build Status](https://ci.ros2.org/job/ci_osx/4719/)

**Comment by sloretz** [comment]
@apojomovsky, I would think even longer is fine (10s)

**Comment by apojomovsky** [comment]
Done @sloretz :)

**Comment by sloretz** [comment]
@apojomovsky Looks like this one is good to merge!

**Pull request merged**
