### PR TITLE
Zero init topic names and types

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Adding a zero_initialized function for rcl_topic_names_and_types_t structure + sanity checks in rcl_get_topic_names_and_types

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Linux: [Build Status](http://ci.ros2.org/job/ci_linux/1830)
OSX: [Build Status](http://ci.ros2.org/job/ci_osx/1365/)
Windows: [Build Status](http://ci.ros2.org/job/ci_windows/1737/)

**Comment by mikaelarguedas** [comment]
please also review https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/63 I cannot put label on this one

**Comment by dirk-thomas** [comment]
While all our usage of the rmw interface goes through rcl anyone could use the rmw interface directly. In that case I think it would be helpful if each implementation would perform the sanity checking itself. Maybe the check can be implemented in a single generic function somewhere which can then be reused by each implementation?

**Comment by wjwwood** [comment]
In my opinion, I don't think it is necessary for each rmw implementation to check it, so long as it is documented. I'd also be fine with a common check function that each calls, but I am not in favor of duplicating the check in each rmw implementation and rcl.

**Comment by mikaelarguedas** [comment]
So I'll go for a common check function in the rmw package that every rmw_implementation can call, sounds good to everyone ?

**Comment by wjwwood** [comment]
That's fine by me.

As I said before, I think it is unnecessary, but it also doesn't hurt to check it explicitly.

**Comment by mikaelarguedas** [comment]
done https://github.com/ros2/rmw/issues/76

**Comment by mikaelarguedas** [comment]
new set of CI with rmw changes:
Linux: [Build Status](http://ci.ros2.org/job/ci_linux/1837)
OSX: [Build Status](http://ci.ros2.org/job/ci_osx/1372/)
Windows: [Build Status](http://ci.ros2.org/job/ci_windows/1744/)

**Comment by mikaelarguedas** [comment]
damn copy paste XD https://github.com/ros2/rcl/blob/master/rcl/include/rcl/node.h#L83

**Comment by wjwwood** [comment]
Oops lol 😄

**Pull request merged**
