### PR TITLE
[Foxy] print RCL_LOCALHOST_ENV_VAR if error happens via rcutils_get_env. (#672)

### PR DESCRIPTION
**Pull request by ivanpauno**
Backports #672 to Foxy.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This should be `--ff-only` instead to avoid diverging `foxy` from `master` while we can.

**Comment by ivanpauno** [comment]
> This should be --ff-only instead to avoid diverging foxy from master while we can.

I will do a merge fast-forward of this PR, the commit hash is exactly the same that the one on master. I opened this, so I get a previous approval of doing the backport.

DCO will fail, as if I sign the commit it will change the hash (though, I don't think that cherry-picked commits need to be re-signed).

**Comment by ivanpauno** [comment]
@jacobperron the PR checker doesn't seem to be working correctly.

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
I don't know what's up the the PR job. Could be an issue with Jenkins. Other than this PR, we haven't had any PR jobs triggered within the last 20 hours.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (after wiping the workspace)

**Pull request merged**
