### PR TITLE
Cmake issues

### LINKED ISSUE #50: services test does not use RMW_IMPLEMENTATION
https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_service.cpp#L31-Lundefined
The name of the services test fixture class should use the RMW_IMPLEMENTATION macro so that the report includes multiple rmw implementations, e.g.

https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_publisher.cpp#L28-L35

### LINKED ISSUE #52: Linking errors for client_fixture and service_fixture tests
The `service_fixture` and `client_fixture` tests are not linking properly on my machine. The rest work fine.

```
Linking CXX executable client_fixture__rmw_connext_cpp
cd /home/dhood/src/rcl/build/rcl/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/client_fixture__rmw_connext_cpp.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++11 -Wall -Wextra    CMakeFiles/client_fixture__rmw_connext_cpp.dir/rcl/client_fixture.cpp.o  -o client_fixture__rmw_connext_cpp  -L/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2 -rdynamic ../librcl__rmw_connext_cpp.so -ldl memory_tools/librcl_memory_tools.so /home/dhood/ros2_ws/install_isolated/rmw_connext_shared_cpp/lib/librmw_connext_shared_cpp.so /home/dhood/ros2_ws/install_isolated/rmw/lib/librmw.so /home/dhood/ros2_ws/install_isolated/rosidl_generator_c/lib/librosidl_generator_c.so /home/dhood/ros2_ws/install_isolated/rosidl_typesupport_connext_cpp/lib/librosidl_typesupport_connext_cpp.so /home/dhood/ros2_ws/install_isolated/rmw_connext_cpp/lib/librmw_connext_cpp.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_introspection_c.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_generator_c.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_introspection_cpp.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_connext_c.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_connext_cpp.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_opensplice_c.so /home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib/libbuiltin_interfaces__rosidl_typesupport_opensplice_cpp.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_introspection_c.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_generator_c.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_introspection_cpp.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_connext_c.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_connext_cpp.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_opensplice_c.so /home/dhood/ros2_ws/install_isolated/example_interfaces/lib/libexample_interfaces__rosidl_typesupport_opensplice_cpp.so -lnddsc -lnddscore -lnddscpp -lrticonnextmsgcpp -lcmxml -lcommonserv -ldcpsgapi -ldcpssac -lddsconfparser -lddsconf -lddsdatabase -lddsi2 -lddskernel -lddsosnet -lddsos -lddsserialization -lddsuser -lddsutil -ldurability -lspliced -ldcpssacpp -lpthread -ldl /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_introspection_c.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_generator_c.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_introspection_cpp.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_connext_c.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_connext_cpp.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_opensplice_c.so /home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib/librcl_interfaces__rosidl_typesupport_opensplice_cpp.so /home/dhood/ros2_ws/install_isolated/rmw_connext_shared_cpp/lib/librmw_connext_shared_cpp.so /home/dhood/ros2_ws/install_isolated/rmw/lib/librmw.so /home/dhood/ros2_ws/install_isolated/rosidl_generator_c/lib/librosidl_generator_c.so /home/dhood/ros2_ws/install_isolated/rosidl_typesupport_connext_cpp/lib/librosidl_typesupport_connext_cpp.so /home/dhood/ros2_ws/install_isolated/rmw_connext_cpp/lib/librmw_connext_cpp.so -ldl -lnddsc -lnddscore -lnddscpp -lrticonnextmsgcpp -lcmxml -lcommonserv -ldcpsgapi -ldcpssac -lddsconfparser -lddsconf -lddsdatabase -lddsi2 -lddskernel -lddsosnet -lddsos -lddsserialization -lddsuser -lddsutil -ldurability -lspliced -ldcpssacpp -lpthread -ldl -Wl,-rpath,/home/dhood/src/rcl/build/rcl:/home/dhood/src/rcl/build/rcl/test/memory_tools:/home/dhood/ros2_ws/install_isolated/rmw_connext_shared_cpp/lib:/home/dhood/ros2_ws/install_isolated/rmw/lib:/home/dhood/ros2_ws/install_isolated/rosidl_generator_c/lib:/home/dhood/ros2_ws/install_isolated/rosidl_typesupport_connext_cpp/lib:/home/dhood/ros2_ws/install_isolated/rmw_connext_cpp/lib:/home/dhood/ros2_ws/install_isolated/builtin_interfaces/lib:/home/dhood/ros2_ws/install_isolated/example_interfaces/lib:/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2:/home/dhood/ros2_ws/install_isolated/rcl_interfaces/lib 
/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2/libnddscore.so: undefined reference to `dlopen'
/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2/libnddscore.so: undefined reference to `dlclose'
/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2/libnddscore.so: undefined reference to `dlerror'
/home/dhood/rti_connext_dds-5.2.0/lib/x64Linux3gcc4.8.2/libnddscore.so: undefined reference to `dlsym'
```

`-ldl` is in the linking output, but I think it might be something similar to [this issue](http://stackoverflow.com/questions/20131138/cmake-add-ldl-at-end-of-link-stage-of-add-library)
I'm on Trusty with gcc version 4.8.4. I think the buildfarm has 4.6.3.

I have seen that the `memory_tools` tests are doing [something specific](https://github.com/ros2/rcl/blob/master/rcl/test/memory_tools/CMakeLists.txt#L16) with `dl` which might be relevant to these tests as well?

### PR DESCRIPTION
**Pull request by jacquelinekay**
Fixes #50 

Also cleans up a useless check in CMake pointed out by @dirk-thomas.

### CODE REVIEW

**Comment by dhood** [comment]
doesn't seem to fix #52

**Comment by dhood** [comment]
what's your gcc version? that's at least one thing I have different to the buildfarm (where everything is fine)

**Comment by jacquelinekay** [comment]
It's 4.6; I just uninstalled 4.6 and replaced it with 4.8 to see if I can reproduce it.

**Comment by dirk-thomas** [comment]
The changes look good to me. If CI is passing and shows the separate test results +1.

**Comment by jacquelinekay** [comment]
I launched CI with `--end-with rcl`.

http://ci.ros2.org/job/ci_linux/1233/
http://ci.ros2.org/job/ci_osx/990
http://ci.ros2.org/job/ci_windows/1272

**Comment by jacquelinekay** [comment]
http://ci.ros2.org/job/ci_linux/1233/testReport/projectroot.home.rosbuild.ci_scripts.ws.src.ros2.rcl/rcl/test_service__rmw_opensplice_cpp/
http://ci.ros2.org/job/ci_linux/1233/testReport/projectroot.home.rosbuild.ci_scripts.ws.src.ros2.rcl/rcl/test_services__rmw_connext_cpp/
http://ci.ros2.org/job/ci_linux/1233/testReport/projectroot.home.rosbuild.ci_scripts.ws.src.ros2.rcl/rcl/test_services__rmw_connext_dynamic_cpp/

**Comment by jacquelinekay** [comment]
it is a bit strange that the second two links that I posted don't have the gtest output that the first one does. But if you look at the console output in the Jenkins job, then it's clear that the test has the correct rmw implementation suffix now.

**Comment by dirk-thomas** [comment]
The first link is for the gtest `test_service` with `rmw_opensplice_cpp`.

The second and third link is for the nosetests `test_service**s**` with `rmw_connext_cpp` and `rmw_connext_dynamic_cpp`.

The second and third test you are interested in are:
* http://ci.ros2.org/job/ci_linux/1233/testReport/projectroot.home.rosbuild.ci_scripts.ws.src.ros2.rcl/rcl/test_service__rmw_connext_cpp/
* http://ci.ros2.org/job/ci_linux/1233/testReport/projectroot.home.rosbuild.ci_scripts.ws.src.ros2.rcl/rcl/test_service__rmw_connext_dynamic_cpp/

**Comment by jacquelinekay** [comment]
ah, thanks for pointing that out

**Pull request merged**
