### PR TITLE
[Backport Foxy] Increased rcl_lifecycle coverage

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Comment by ahcorde** [comment]
Compiling `rcl_lifecycle` and testing `rcl_lifecycle`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12661/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7624/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10374/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12596/)

**Comment by brawner** [comment]
The Fpr job fails on these tests. I think there is a fix that needs to be released for these to work

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by ahcorde** [comment]
@brawner CI is green!

**Review by brawner — APPROVED** [review]

**Pull request merged**
