### PR TITLE
free valid_transitions for all states

### PR DESCRIPTION
**Pull request by vmayoral**
Follows from https://github.com/ros2/rcl/pull/509

### CODE REVIEW

**Comment by vmayoral** [comment]
@clalancette, @dirk-thomas ping in here.

**Comment by clalancette** [comment]
Thanks.  I'll re-kick linux CI to see if the regression is still there:

CI: * Linux [Build Status](http://ci.ros2.org/job/ci_linux/8710/)

**Comment by clalancette** [comment]
All right, looking good.  I'll run a slightly more complete CI across all of the platforms; assuming that comes back clean, I'm happy with this.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8712/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4545/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7115/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8628/)

**Comment by clalancette** [comment]
All right, I'm happy with this now.  Thanks @vmayoral !

**Pull request merged**
