### PR TITLE
Avoid dynamic allocation of message before sending over rosout

### PR DESCRIPTION
**Pull request by cwecht**
This PR provides an approach for filling the messages send over rosout without involving additional heap allocations. I might miss something here, but for me this approach seems more reasonable - at least regard performance.

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
CI is unhappy about a few stylistic things in here.  Once that is fixed, we can do a full review.

**Comment by cwecht** [comment]
> CI is unhappy about a few stylistic things in here. Once that is fixed, we can do a full review.

Done: cpplint and uncrustify are happy now.

**Review by clalancette — APPROVED** [review]
Looks reasonable to me, and should avoid some allocations/copies.  Thanks!

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18720/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13246/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19454/)

**Pull request merged**
