### PR TITLE
[Backport Foxy] Increased RCL coverage 

### PR DESCRIPTION
**Pull request by ahcorde**
Increased RCL coverage.

 - #684
 - #691
 - #681
 - #680
 - #683
 - #688 
 - #685
 - #682

### CODE REVIEW

**Comment by ahcorde** [comment]
Compiling up-to `rcl` and testing `rcl`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12659/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7622/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10372/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12594/)

**Comment by brawner** [comment]
Rebuilding windows. That failure doesn't seem related
[Build Status](https://ci.ros2.org/job/ci_windows/12602/)

**Comment by ahcorde** [comment]
Rebuilding Windows

[Build Status](https://ci.ros2.org/job/ci_windows/12716/)

**Comment by ahcorde** [comment]
@brawner CI is green!

**Review by brawner — APPROVED** [review]

**Pull request merged**
