### PR TITLE
fix: Make flaky timer tests work

### PR DESCRIPTION
**Pull request by jmachowinski**
This might fix the regression that was reportet by @clalancette.

Note, it does not fail on my local machine, and therefore I can not verify if it fixes the issue.

### CODE REVIEW

**Comment by clalancette** [comment]
> Note, it does not fail on my local machine, and therefore I can not verify if it fixes the issue.

Hm, that's surprising.  It fails like 90% of the time locally for me.

**Comment by clalancette** [comment]
Here's just Linux CI with this:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20676/)

**Comment by clalancette** [comment]
Actually, the build farm is quiet, so here are jobs on all platforms just in case this fixes it:

* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14998/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21372/)

**Comment by jmachowinski** [comment]
hm, still fails.

**Comment by jmachowinski** [comment]
> Hm, that's surprising. It fails like 90% of the time locally for me.
My failure, I was still on a rclcpp version before the merge of https://github.com/ros2/rclcpp/pull/2142

This PR is obsolete and supersedes by https://github.com/ros2/rcl/pull/1146

**Pull request closed without merging**
