### PR TITLE
Revert "improved rcl_wait in the area of timeout computation and spur…

### PR DESCRIPTION
**Pull request by clalancette**
…ious wakeups (#1135)"

This reverts commit 3c6c5dc47dac23d70722a60b2c0a387d2e71b71d.

The combination of this and https://github.com/ros2/rclcpp/pull/2142 seems to be causing regressions on the buildfarm; see https://ci.ros2.org/job/ci_linux/20668/#showFailuresLink for the results.

For now, let's revert this one to get CI back to green.  @mjcarroll @wjwwood @jmachowinski FYI

### CODE REVIEW

**Comment by clalancette** [comment]
Here's a full CI run on Linux on the current code:  [Build Status](http://ci.ros2.org/job/ci_linux/20670/)

And here is full CI with it reverted (i.e. this PR applied):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20671/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14997/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21371/)

**Comment by jmachowinski** [comment]
@clalancette can you run the CI with https://github.com/ros2/rcl/pull/1143 ?

**Comment by wjwwood** [comment]
I played around with #1143 a bit but was unable to fix all the tests with it. I think it's a good start, but in order to avoid these tests failing over the weekend, I'm going to go forward with this revert and then work on re-reverting it next week with a fix like #1143.

Note the tests that failed in https://github.com/ros2/rcl/pull/1142#issuecomment-2027547770 are known flakes that are (in my opinion) unrelated to this change.

**Comment by wjwwood** [comment]
Follow up CI for rolling, to see that this was effective post merge:

- Linux: [Build Status](https://ci.ros2.org/job/ci_linux/20678/)

**Pull request merged**
