### PR TITLE
Implement service info structure with timestamps.

### PR DESCRIPTION
**Pull request by iluetkeb**
This implements the RCL part of https://github.com/ros2/rmw/issues/219

It requires  https://github.com/ros2/rmw/pull/217 and https://github.com/ros2/rmw_implementation/pull/96 to build. An example implementation is in https://github.com/ros2/rmw_fastrtps/pull/369.

### CODE REVIEW

**Comment by iluetkeb** [comment]
> I'd prefer to replace the existing functions, but I know there's not time for that. I guess we'll have to do two deprecation cycles over three releases to get back to just rcl_take_X...

I already did a fair amount of work in that direction, but I figured I needed a quicker way. I'm happy to continue in that direction, then maybe we can get this in earlier.

**Comment by wjwwood** [comment]
So, the only thing we could do in the near future that would be better, is to deprecate the old signature and update our use of it in rclpy and rclcpp. That way we could remove it in the next version, rename the current one and deprecate its original name, so that in f+2 turtle we could be at the ideal state... Not deprecating it now just means we have to live with it (renaming or not) for an additional cycle, but that's not the end of the world.

So, while not optimal, I think the current state is fine, tbh.

**Comment by iluetkeb** [comment]
What do I need to do to deprecate it?

**Comment by wjwwood** [comment]
> What do I need to do to deprecate it?

Documentation and there are compiler attributes for that.

> Oh, does this mean I would have to update all the current usages? There are very many of those, I don't think I'll manage that in time.

Yes.

**Comment by iluetkeb** [comment]
btw, I'm currently still working on the rclpy stuff. it's implemented, but there is a double-free somewhere that I'm hunting down.

**Comment by iluetkeb** [comment]
So. This should be ready.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-middleware-change-proposal/15863/7

**Pull request merged**
