### PR TITLE
Add ~/get_type_description service (rep2011) (dupe of #1052)

### PR DESCRIPTION
**Pull request by james-rms**
Dupe of https://github.com/ros2/rcl/pull/1052 , rebased to fix a test.

### CODE REVIEW

**Comment by james-rms** [comment]
Gist: https://gist.githubusercontent.com/james-rms/e1c0c45c7e56d86cb09c5bbc28aa5f72/raw/ef08db1b38130acc2c1b27715c98cf640f14e24c/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl rcl_action
TEST args:  --packages-above rcl rcl_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11833
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18482/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13030/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19202/)

**Comment by clalancette** [comment]
Instead of a completely new PR, can we just open a PR to that PR?  It will keep all of the history intact.

**Comment by achim-k** [comment]
> Instead of a completely new PR, can we just open a PR to that PR? It will keep all of the history intact.

This would then be a new PR on top of #1052 with a single merge commit?

**Comment by clalancette** [comment]
> This would then be a new PR on top of #1052 with a single merge commit?

In general, we like to keep all development of a branch in one PR.  If we need to rebase #1052, then please feel free to do that.  If we need to add new PRs on top of #1052 , then please just push them there.  And then close this PR.

The only reasons to open a new PR is if we want to split some work out, or if the original author is not responding and we can't push to their fork anymore for some reason.

**Comment by achim-k** [comment]
OK, I have rebased #1052 so I believe we can close this PR

**Comment by clalancette** [comment]
> OK, I have rebased #1052 so I believe we can close this PR

OK, sounds good.  Will close this one out.  @james-rms If we need this one for some reason, please feel free to reopen.

**Pull request closed without merging**
